CREATE TABLE IF NOT EXISTS `sys_files` (
 `id` VARCHAR(255) NOT NULL COMMENT '文件UUID',
 `name` VARCHAR(255) NOT NULL COMMENT '文件名称',
 `url` VARCHAR(255) NOT NULL COMMENT '文件地址',
 `ext` VARCHAR(255) NOT NULL COMMENT '文件后缀类型',
 `create_time` VARCHAR(255) NOT NULL COMMENT '创建时间',
 `update_time` VARCHAR(255) NOT NULL COMMENT '更新时间',
 `state` DOUBLE PRECISION NOT NULL COMMENT '数据状态值 -1 删除 0 失效 1 正常',
 `status` DOUBLE PRECISION NOT NULL COMMENT '业务状态值',
 `created_at` DATETIME NOT NULL,
 `updated_at` DATETIME NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB COMMENT '系统文件' DEFAULT CHARSET=utf8mb4;
